services:
  ecom:
    image: nginx:alpine
    container_name: ecom
    volumes:
      - ./ecomFrontend:/usr/share/nginx/html
    expose:
      - 80
  # admin:
  #   image: nginx:alpine
  #   container_name: admin
  #   volumes:
  #     - ./PayinPayoutAdmin:/usr/share/nginx/html
  #   expose:
  #     - 80
  
  # user:
  #   image: nginx:alpine
  #   container_name: user
  #   volumes:
  #     - ./PayinpayoutUser:/usr/share/nginx/html
  #   expose:
  #     - 80
  # devuser:
  #   image: nginx:alpine
  #   container_name: devuser
  #   volumes:
  #     - ../dev/PayinPayout/User/build:/usr/share/nginx/html
  #   expose:
  #     - 80
  # devadmin:
  #   image: nginx:alpine
  #   container_name: devadmin
  #   volumes:
  #     - ../dev/PayinPayout/Admin/build:/usr/share/nginx/html
  #   expose:
  #     - 80
  wrapping:
    image: nginx:alpine
    container_name: wrapping
    volumes:
      - ./WrappingStudio:/usr/share/nginx/html
    expose:
      - 80
  wrappingvendor:
    image: nginx:alpine
    container_name: wrappingvendor
    volumes:
      - ./WrappingVendor:/usr/share/nginx/html
    expose:
      - 80
  newEcomUser:
    image: nginx:alpine
    container_name: newEcomUser
    volumes:
      - ./NewEcom/User:/usr/share/nginx/html
    expose:
      - 80
  newEcomVendor:
    image: nginx:alpine
    container_name: newEcomVendor
    volumes:
      - ./NewEcom/Vendor:/usr/share/nginx/html
    expose:
      - 80
  bankmudrauser:
    image: nginx:alpine
    container_name: bankmudrauser
    volumes:
      - ./BankMudra:/usr/share/nginx/html
    expose:
      - 80
  devbankmudrauser:
    image: nginx:alpine
    container_name: devbankmudrauser
    volumes:
      - ./dev/BankMudra:/usr/share/nginx/html
    expose:
      - 80
  ecom-server:
    build:
      context: ../ecomm/server
    container_name: ecomm-server
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - ecom
  wrapping-server:
    build:
      context: ../wrappingstudio/Server
    container_name: wrapping-server
    ports:
      - "3500:3500"
    restart: always
    depends_on:
      - wrapping
  bankmudra-server:
    build:
      context: ../merchant-backend
    container_name: bankmudra-server
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - bankmudrauser
  # server:
  #   build:
  #     context: ../PayinPayout/Backend   # relative to docker-compose.yml
  #   container_name: payinpayout-server
  #   ports:
  #     - "3000:3000"
  #   restart: always
  #   depends_on:
  #     - user
  #     - admin
  # dev-server:
  #   build:
  #     context: ../dev/PayinPayout/Backend  
  #   container_name: devpayinpayout-server
  #   ports:
  #     - "3001:3000"
  #   restart: always
  #   depends_on:
  #     - devuser
  #     - devadmin
  nginx:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      -  /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ecomFrontend:/var/www/ecom
      - ./WrappingVendor:/var/www/wrappingvendor
      # - ./PayinPayoutAdmin:/var/www/admin
      # - ./PayinpayoutUser:/var/www/user
      - ./WrappingStudio:/var/www/wrapping
      - ./BankMudra:/var/www/bankmudra
      - ./NewEcom/Vendor:/var/www/newEcomVendor
      - ./NewEcom/User:/var/www/newEcomUser
      - ./dev/BankMudra:/var/www/devbankmudra
      # - ../dev/PayinPayout/User/build:/var/www/devuser
      # - ../dev/PayinPayout/Admin/build:/var/www/devadmin
    depends_on:
      - ecom
      # - admin
      # - user
      - wrapping
      - wrappingvendor
      - bankmudrauser
      - newEcomUser
      - newEcomVendor
      # - devuser
      # - devadmin
